CONFIG = {
    "dataset_root": "视频解析智能体数据包/hackathon_release",
    "split": "dev",
    "output": "vqa_output.json",
    "questions_per_segment": 4,
    "keyframes_per_segment": 3,
    "multiple_choice_num_options": 4,
    "use_mllm": False,
    "send_images": False,
    "template_fallback_on_mllm_error": False,
    "generation_call_timeout": 150,
    "generation_retries": 2,
    "concurrency": 16,
    "clips_dir": "视频解析智能体数据包/hackathon_release/vqa/clips",
    "api": {
        "base_url": "https://api.openai.com/v1",
        "model": "deepseek-v4-pro",
        "api_key": "",
        "timeout": 120,
        "temperature": 0.2,
        "max_tokens": 8192,
        "use_response_format": True,
    },
}
